apiVersion: v1
kind: Service
metadata:
  name: python-upstream-service
spec:
  selector:
    app: python-upstream-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
